### ISSUE TITLE
Error Could not find 'print'

### ISSUE THREAD

**Issue by mvital78** [Append-IT/Blazor.Printing#13]
Hello everyone! I'm trying to use the library in my Blazor Server project. But I get an error message. (trying to print Base64).

Microsoft.JSInterop.JSException: "Could not find 'print' ('print' was undefined).
Error: Could not find 'print' ('print' was undefined).
    at https://localhost/_framework/blazor.server.js:2:29250
    at Array.forEach (<anonymous>)
    at n.value (https://localhost/_framework/blazor.server.js:2:29211)
    at w (https://localhost/_framework/blazor.server.js:2:28290)
    at https://localhost/_framework/blazor.server.js:2:30739
    at new Promise (<anonymous>)
    at i.beginInvokeJSFromDotNet (https://localhost/_framework/blazor.server.js:2:30713)
    at https://localhost/_framework/blazor.server.js:2:111546
    at Array.forEach (<anonymous>)
    at i.value (https://localhost/_framework/blazor.server.js:2:111517)"

P.S. one more note. I use Blazor.Polifyll to make the app run on the older devices. Even if I include the print.js in my project, it doesn't work.

Maybe someone knows what the problem is?

VG

var test = await DokumentService.PrintPdfFile(selectedItems.Select(s=>s.DocumentId).ToList());
await PrintingService.Print(new PrintOptions(test) { Base64 = true });

**Comment by edelchristian93** [comment]
What was the solution? I have the same problem.
