### ISSUE TITLE
printJS is not defined

### ISSUE THREAD

**Issue by 14z0r** [Append-IT/Blazor.Printing#22]
Hello, 

if i try to print my PDF, i get the error, that the printJS was not found. 

`blazor.server.js:1  [2023-06-29T10:25:53.508Z] Error: Microsoft.JSInterop.JSException: printJS is not defined
ReferenceError: printJS is not defined
    at Module.print (http://localhost:5019/_content/Append.Blazor.Printing/scripts.js:3:5)
    at http://localhost:5019/_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (http://localhost:5019/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (http://localhost:5019/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (http://localhost:5019/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (http://localhost:5019/_framework/blazor.server.js:1:67009)
    at i.onmessage (http://localhost:5019/_framework/blazor.server.js:1:51322)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Append.Blazor.Printing.PrintingService.Print(PrintOptions options)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`

**Comment by vertonghenb** [comment]
Not sure if this is still the case?
@14z0r
