### ISSUE TITLE
Microsoft.JSInterop.JSException: Missing printable information in Blazor server

### ISSUE THREAD

**Issue by MrYossu** [Append-IT/Blazor.Printing#31]
I just tried the sample code, and wanted to test printing from a Base-64 encoded string from Blazor server.

I copied the `base64String` variable from the Documentation project's `Base64.razor` file into the server project's Index.razor file, and then copied the button...

```html
<button type="button" @onclick="@(() => PrintingService.Print(new PrintOptions(base64String) {Base64 = true }))">
  Print Base64 PDF
</button>
```

(I changed the button caption to distinguish the two buttons).

However, when I click the button, I get an exception...

>Microsoft.JSInterop.JSException: Missing printable information.
>Error: Missing printable information.
    at L (https://localhost:44364/_content/Append.Blazor.Printing/scripts.js:1:13523)
    at Module.print (https://localhost:44364/_content/Append.Blazor.Printing/scripts.js:3:5)
    at https://localhost:44364/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:44364/_framework/blazor.server.js:1:3475)
    at https://localhost:44364/_framework/blazor.server.js:1:72077
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:44364/_framework/blazor.server.js:1:72063)
    at kt._processIncomingData (https://localhost:44364/_framework/blazor.server.js:1:70105)
    at connection.onreceive (https://localhost:44364/_framework/blazor.server.js:1:64508)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Append.Blazor.Printing.PrintingService.Print(PrintOptions options) in D:\Blazor.Printing-master\source\Append.Blazor.Printing\PrintingService.cs:line 27
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Anyone any idea how to get this working? I already have code that generates PDF files as `byte[]`, and a helper method to return this as a Base-64 encoded string, so I'd like to use that. I don't want to have to save the file to disk.

Thanks

**Comment by MrYossu** [comment]
Hmm, restarted the app and it worked!
